server:
  port: 3000
  #\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cwgl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /admin/
      suffix: .jsp
  #redis
  redis:
    #redis数据库地址
    host: 192.168.100.130
    port: 6379
    timeout: 1000
    #redis数据库索引，默认0
    database: 0
    jedis:
      pool:
        max-wait: 10000
# Dubbo
dubbo:
  scan: cn.dc.fms.service.remote
  application:
    name: finance-fms-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20010
  registry:
    #address: 192.168.100.128:2181
    #,zookeeper://192.168.100.128:2182,zookeeper://192.168.100.128:2183
    #id: my-registry
    protocol: zookeeper
    address: zkserver:2181,zkserver:2182,zkserver:2183
  consumer:
    timeout: 9000
