#server
server:
  port: 2000
# Dubbo \u670D\u52A1\u63D0\u4F9B\u8005\u914D\u7F6E
dubbo:
  scan: cn.dc.permission.service
  application:
    name: finance-usercenter-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20000
  registry:
    #address: 192.168.100.128:2181
    #,zookeeper://192.168.100.128:2182,zookeeper://192.168.100.128:2183
    #id: my-registry
    protocol: zookeeper
    address: zkserver:2181,zkserver:2182,zkserver:2183
  consumer:
    timeout: 9000
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zheng?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #redis
  redis:
    #redis数据库地址
    host: 192.168.100.130
    port: 6379
    timeout: 1000
    #redis数据库索引，默认0
    database: 0
    jedis:
      pool:
        max-wait: 10000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:cn.dc.permission.mapper/*.xml
